# History Limit
set-option -g history-limit 100000

# Create Log Directory
run-shell "mkdir -p ~/.local/tmux_logs"

set-hook -g session-created "run-shell 'tmux pipe-pane -o -t #{session_name}:#{window_id}.#{pane_index} \"cat >> ~/.local/tmux_logs/#{session_name}-#{window_id}-#{pane_index}-`date +\"%Y-%m-%d_%H:%M:%S\"`.log\"'"
set-hook -g after-new-window "run-shell 'tmux pipe-pane -o -t #{session_name}:#{window_id}.#{pane_index} \"cat >> ~/.local/tmux_logs/#{session_name}-#{window_id}-#{pane_index}-`date +\"%Y-%m-%d_%H:%M:%S\"`.log\"'"
set-hook -g after-split-window "run-shell 'tmux pipe-pane -o -t #{session_name}:#{window_id}.#{pane_index} \"cat >> ~/.local/tmux_logs/#{session_name}-#{window_id}-#{pane_index}-`date +\"%Y-%m-%d_%H:%M:%S\"`.log\"'"

set-hook -g pane-exited "run-shell 'tmux pipe-pane -o -t #{session_name}:#{window_id}-#{pane_index} \"cat >> ~/.local/tmux_logs/#{session_name}-#{window_id}-#{pane_index}-`date +\"%Y-%m-%d_%H:%M:%S\"`.log\"'"
set-hook -g pane-focus-in "run-shell 'tmux pipe-pane -o -t #{session_name}:#{window_id}-#{pane_index} \"cat >> ~/.local/tmux_logs/#{session_name}-#{window_id}-#{pane_index}-`date +\"%Y-%m-%d_%H:%M:%S\"`.log\"'"
