#!/bin/bash
# validate-commit-message.sh
# Shared commit message validation library
# Single source of truth for commit message rules.
#
# Sourced by:
#   - hooks/commit-msg          (git hook — terminal-side gate)
#   - global/hooks/commit-message-guard.sh (PreToolUse — Claude-side feedback loop)
#
# Usage:
#   . /path/to/validate-commit-message.sh
#   if ! validate_commit_message "feat: add feature"; then
#       echo "invalid" >&2
#   fi

# Allowed commit types (Conventional Commits)
readonly CMV_TYPES="feat|fix|docs|style|refactor|perf|test|build|ci|chore|security"

# AI attribution patterns — single source of truth shared with attribution-guard
# (PR/issue body / release notes checks). Same patterns enforced across commit
# messages, PR titles/bodies, issue titles/bodies, release notes, and PR
# review bodies so an attribution leak cannot slip through one channel while
# being blocked in another.
#
# Three-pattern design (was: single broad case-insensitive prose match) —
# the broad form caused false positives on legitimate technical writing
# ("docs: clarify Claude API behavior", "feat: add Anthropic SDK"). The
# patterns below target the actual leak shapes seen in practice:
#
#   1. Trailer-style attribution at line start:
#        Co-Authored-By: Claude
#        Generated-by: Claude
#        Authored-by: Anthropic
#   2. Bot emoji adjacent to Claude/Anthropic:
#        🤖 Claude
#        🤖 Generated by Anthropic
#   3. "Generated|Created|Authored {with|by|using} {Claude|Anthropic}" prose:
#        Generated with Claude
#        Created by Anthropic
#
# Casual prose mentions ("Claude API", "Anthropic SDK", "AI-assisted refactor")
# are deliberately allowed — they describe what the code interacts with, not
# who authored the change.
readonly CMV_ATTRIBUTION_TRAILER_REGEX='^[[:space:]]*(Co-[Aa]uthored-[Bb]y|Co-[Aa]uthor|[Gg]enerated[- ]?[Bb]y|[Cc]reated[- ]?[Bb]y|[Aa]uthored[- ]?[Bb]y|[Ss]igned-[Oo]ff-[Bb]y|[Aa]ssisted-[Bb]y)[[:space:]]*:[[:space:]]*.*([Cc]laude|[Aa]nthropic|AI[- ]?[Aa]ssisted)'
readonly CMV_ATTRIBUTION_EMOJI_REGEX='🤖[[:space:]]*[^[:space:]]*[[:space:]]*([Cc]laude|[Aa]nthropic)'
readonly CMV_ATTRIBUTION_PROSE_REGEX='([Gg]enerated|[Cc]reated|[Aa]uthored|[Ww]ritten)[[:space:]]+(with|by|using)[[:space:]]+(Claude|Anthropic|AI[- ]?[Aa]ssistant)'

# Back-compat alias retained because external scripts and tests grep for this
# symbol. Set to the trailer pattern (the strongest signal of intent).
readonly CMV_ATTRIBUTION_REGEX="$CMV_ATTRIBUTION_TRAILER_REGEX"

# validate_no_attribution <text>
# Returns 0 if text contains no AI/Claude attribution, 1 if attribution is found.
# On failure, prints reason to stderr.
#
# Used by both validate_commit_message (this file) and attribution-guard.sh
# (the PR/issue/release-notes/review-body PreToolUse hook) so the patterns
# stay in one place.
validate_no_attribution() {
    local text="$1"

    if [ -z "$text" ]; then
        return 0
    fi

    # Pattern 1: trailer-style attribution. grep -E with `^` anchors per line
    # in multiline input, so a "Co-Authored-By: Claude" trailer is caught
    # regardless of surrounding prose, while a one-liner that merely
    # references the same words inside a sentence is allowed.
    if printf '%s' "$text" | grep -qE "$CMV_ATTRIBUTION_TRAILER_REGEX"; then
        echo "Text contains AI/Claude attribution trailer (Co-Authored-By: / Generated-by: / Authored-by: Claude or Anthropic). Remove the trailer before submitting." >&2
        return 1
    fi

    # Pattern 2: bot emoji directly adjacent to Claude/Anthropic.
    if printf '%s' "$text" | grep -qE "$CMV_ATTRIBUTION_EMOJI_REGEX"; then
        echo "Text contains AI bot emoji adjacent to Claude/Anthropic attribution. Remove the marker before submitting." >&2
        return 1
    fi

    # Pattern 3: "Generated with Claude" / "Created by Anthropic" prose.
    if printf '%s' "$text" | grep -qE "$CMV_ATTRIBUTION_PROSE_REGEX"; then
        echo "Text contains AI/Claude attribution prose (e.g. 'Generated with Claude', 'Created by Anthropic'). Remove the attribution before submitting." >&2
        return 1
    fi

    return 0
}

# validate_commit_message <message>
# Returns 0 on valid, 1 on invalid.
# On failure, prints reason to stderr.
validate_commit_message() {
    local msg="$1"

    # Rule 1: Conventional Commits format — type(scope)?: description
    if ! printf '%s' "$msg" | grep -qE "^($CMV_TYPES)(\([a-z0-9._-]+\))?: .+"; then
        echo "Commit message must follow Conventional Commits: 'type(scope): description' or 'type: description'. Allowed types: ${CMV_TYPES//|/, }." >&2
        return 1
    fi

    # Extract description (everything after the first ': ')
    local desc
    desc=$(printf '%s' "$msg" | sed -E 's/^[^:]*:[[:space:]]*//')

    # Rule 2: Description starts with a lowercase ASCII letter
    # Gated by CLAUDE_CONTENT_LANGUAGE (see issue #410):
    #   - english (default) / unset → enforce lowercase ASCII
    #   - korean_plus_english → allow Hangul first char as well
    #   - any → skip first-char check (Conv. Commits type is still enforced)
    # The Conventional Commits type/scope portion (feat, fix, etc.) stays
    # ASCII-only under every policy — only the description is relaxed.
    local policy="${CLAUDE_CONTENT_LANGUAGE:-english}"
    case "$policy" in
        any)
            : ;;
        korean_plus_english)
            if ! printf '%s' "$desc" | perl -CSDA -ne '
                exit 1 unless /^[a-z\x{AC00}-\x{D7A3}\x{1100}-\x{11FF}\x{3130}-\x{318F}]/
            ' 2>/dev/null; then
                echo "Commit message description must start with a lowercase letter or a Hangul character (CLAUDE_CONTENT_LANGUAGE=korean_plus_english)." >&2
                return 1
            fi
            ;;
        *)
            local first_char
            first_char=$(printf '%s' "$desc" | head -c1)
            case "$first_char" in
                a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z) ;;
                *)
                    echo "Commit message description must start with a lowercase letter." >&2
                    return 1
                    ;;
            esac
            ;;
    esac

    # Rule 3: No trailing period
    case "$desc" in
        *.)
            echo "Commit message description must not end with a period." >&2
            return 1
            ;;
    esac

    # Rule 4: No AI/Claude attribution (delegates to shared helper for SSOT)
    if ! validate_no_attribution "$msg" 2>/dev/null; then
        echo "Commit message must not contain AI/Claude attribution (claude, anthropic, ai-assisted, generated with, co-authored-by: claude)." >&2
        return 1
    fi

    # Rule 5: No emojis
    # perl exits 1 when a match is found; 0 otherwise.
    if ! printf '%s' "$msg" | perl -CSD -ne 'exit 1 if /[\x{1F300}-\x{1F9FF}\x{2600}-\x{26FF}\x{2700}-\x{27BF}\x{1F1E0}-\x{1F1FF}]/' 2>/dev/null; then
        echo "Commit message must not contain emojis." >&2
        return 1
    fi

    return 0
}
