#!/bin/bash
# Test suite: attribution-guard.sh — three-pattern attribution detection +
# extended scope (issue #480).
# Run: bash tests/hooks/test-attribution-guard.sh
#
# Patterns under test:
#   1. Trailer-style attribution (anchored at line start)
#   2. Bot emoji 🤖 adjacent to Claude/Anthropic
#   3. "Generated|Created|Authored {with|by|using} {Claude|Anthropic}" prose
#
# Scope under test (issue #480 extended): gh pr create|edit|comment|review,
# gh issue create|edit|comment, gh release create|edit. Inspected fields:
# --title/-t, --body/-b, --notes/-n.

HOOK="global/hooks/attribution-guard.sh"
PASS=0
FAIL=0
ERRORS=()

cd "$(dirname "$0")/../.." || exit 1

assert_decision() {
    local label="$1"
    local expected="$2"
    local cmd="$3"

    local payload
    payload=$(jq -cn --arg c "$cmd" '{tool_input:{command:$c}}')
    local result
    result=$(printf '%s' "$payload" | bash "$HOOK" 2>/dev/null)

    if echo "$result" | grep -q "\"$expected\""; then
        PASS=$((PASS + 1))
        echo "  PASS: $label"
    else
        FAIL=$((FAIL + 1))
        ERRORS+=("FAIL: $label — expected $expected, got: $result")
        echo "  FAIL: $label"
    fi
}

echo "=== attribution-guard.sh tests ==="
echo ""

echo "[deny: trailer-style attribution at line start]"

# Trailer in PR body (multi-line, trailer on its own line)
assert_decision "PR create: 'Co-authored-by: Claude' trailer in --body → deny" "deny" \
    'gh pr create --title "fix: bug" --body "Implements feature X.

Co-authored-by: Claude <noreply@anthropic.com>"'

# Generated-by trailer in PR body
assert_decision "PR create: 'Generated-by: Claude' trailer in --body → deny" "deny" \
    'gh pr create --title "feat: ship" --body "Adds new endpoint.

Generated-by: Claude"'

# Authored-by trailer with Anthropic
assert_decision "issue create: 'Authored-by: Anthropic' trailer in --body → deny" "deny" \
    'gh issue create --title "Bug report" --body "Steps to reproduce ...

Authored-by: Anthropic"'

# AI-Assisted trailer
assert_decision "PR comment: 'Assisted-By: AI-Assisted' trailer in --body → deny" "deny" \
    'gh pr comment 5 --body "Reviewed.

Assisted-By: AI-Assisted"'

echo ""
echo "[deny: bot emoji adjacent to Claude/Anthropic]"

assert_decision "PR review: '🤖 Claude' in --body → deny" "deny" \
    'gh pr review 5 --body "🤖 Claude reviewed this change"'

assert_decision "release edit: '🤖 generated by Anthropic' in --notes → deny" "deny" \
    'gh release edit v1.0 --notes "🤖 generated by Anthropic"'

echo ""
echo "[deny: 'Generated|Created|Authored {with|by|using}' prose]"

assert_decision "PR review: 'Generated with Claude' prose → deny" "deny" \
    'gh pr review 5 --body "Generated with Claude"'

assert_decision "release create: 'Created by Anthropic' prose in --notes → deny" "deny" \
    'gh release create v1.0 --notes "Created by Anthropic"'

assert_decision "PR create: 'Generated by Claude' prose in --body → deny" "deny" \
    'gh pr create --title "feat: x" --body "Implements X.

Generated by Claude"'

echo ""
echo "[deny: scope extension — pr review + release create|edit]"

assert_decision "pr review --body trailer → deny (scope #480)" "deny" \
    'gh pr review 5 --body "LGTM.

Co-authored-by: Claude"'

assert_decision "release create --notes trailer → deny (scope #480)" "deny" \
    'gh release create v1.0 --notes "Notes ...

Co-authored-by: Claude"'

assert_decision "release edit -n short flag trailer → deny (scope #480)" "deny" \
    'gh release edit v1.0 -n "Notes ...

Generated-by: Claude"'

echo ""
echo "[allow: false-positive prevention — casual technical prose]"

# These were denied by the old broad regex; the new three-pattern design
# treats them as legitimate technical writing.
assert_decision "PR create: casual 'Claude API' mention in --title → allow" "allow" \
    'gh pr create --title "docs: clarify Claude API behavior" --body "Adds notes."'

assert_decision "PR create: casual 'Anthropic SDK' mention in --body → allow" "allow" \
    'gh pr create --title "feat: integrate" --body "Adds Anthropic SDK integration tests."'

assert_decision "release create: 'Compatible with Claude 4.7' in --notes → allow" "allow" \
    'gh release create v1.0 --notes "Compatible with Claude 4.7 models."'

assert_decision "issue create: 'AI-assisted refactor' prose → allow" "allow" \
    'gh issue create --title "AI-assisted refactor proposal" --body "Discussion thread."'

assert_decision "PR comment: 'per Anthropic docs' in --body → allow" "allow" \
    'gh pr comment 5 --body "Implemented per Anthropic docs."'

echo ""
echo "[allow: clean text + parser deferrals + out-of-scope]"

assert_decision "clean PR create → allow" "allow" \
    'gh pr create --title "feat(api): add login endpoint" --body "Adds POST /auth/login"'

assert_decision "--body-file deferred → allow" "allow" \
    'gh pr create --title "feat: add ui" --body-file pr-body.md'

assert_decision "--notes-file deferred → allow" "allow" \
    'gh release create v1.0 --notes-file CHANGELOG.md'

assert_decision '$(...) command-substituted body → allow' "allow" \
    'gh pr create --title "feat: ship" --body "$(cat body.md)"'

assert_decision "out-of-scope (gh repo view) → allow" "allow" \
    'gh repo view --json name,description'

assert_decision "out-of-scope (gh release upload) → allow" "allow" \
    'gh release upload v1.0 binary.zip'

echo ""
echo "=== Results: $PASS passed, $FAIL failed ==="
if [ ${#ERRORS[@]} -gt 0 ]; then
    echo ""
    for err in "${ERRORS[@]}"; do
        echo "  $err"
    done
    exit 1
fi
exit 0
